# Checks the child cache and the actual toolchain emulator, including list order.
function(check_node_configuration binary_dir node flags)
  # An independent parent-cache comparison also detects omissions in the outer CTest command.
  file(READ "${TEST_PARENT_BINARY_DIR}/CMakeCache.txt" parent_cache)
  set(parent_flags "")
  if(parent_cache MATCHES "(^|[\r\n])NODE_JS_FLAGS:[^=]*=([^\r\n]*)")
    set(parent_flags "${CMAKE_MATCH_2}")
  endif()
  if(NOT flags STREQUAL parent_flags)
    message(FATAL_ERROR "Outer driver Node flags '${flags}', parent selected '${parent_flags}'.")
  endif()
  file(READ "${binary_dir}/CMakeCache.txt" cache)
  if(NOT cache MATCHES "(^|[\r\n])NODE_JS_FLAGS:[^=]*=([^\r\n]*)")
    message(FATAL_ERROR "${binary_dir}: NODE_JS_FLAGS missing from child cache.")
  endif()
  set(actual_flags "${CMAKE_MATCH_2}")
  if(NOT actual_flags STREQUAL flags)
    message(FATAL_ERROR "${binary_dir}: child Node flags '${actual_flags}', expected '${flags}'.")
  endif()
  file(READ "${binary_dir}/node-emulator.txt" emulator)
  if(NOT emulator STREQUAL "${node};${flags}")
    message(FATAL_ERROR "${binary_dir}: emulator '${emulator}', expected '${node};${flags}'.")
  endif()
  message(STATUS "${binary_dir}: child Node flags and emulator order verified: ${emulator}")
endfunction()
