# Distributed under the Boost Software License, Version 1.0.
# Native install-preset round trip. VERIFY_ROOT is exactly VERIFY_PARENT/execution-packages.
cmake_minimum_required(VERSION 3.24)
foreach(required EXECUTION_SOURCE TOOLKIT_SOURCE VERIFY_PARENT VERIFY_ROOT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Required path: ${required}")
  endif()
endforeach()
file(REAL_PATH "${EXECUTION_SOURCE}" EXECUTION_SOURCE)
file(REAL_PATH "${TOOLKIT_SOURCE}" TOOLKIT_SOURCE)
cmake_path(ABSOLUTE_PATH VERIFY_PARENT NORMALIZE OUTPUT_VARIABLE parent)
cmake_path(ABSOLUTE_PATH VERIFY_ROOT NORMALIZE OUTPUT_VARIABLE root)
if(EXISTS "${parent}")
  file(REAL_PATH "${parent}" parent)
endif()
if(EXISTS "${root}")
  file(REAL_PATH "${root}" root)
endif()
cmake_path(IS_PREFIX parent "${root}" NORMALIZE in_scope)
if(NOT in_scope OR NOT root STREQUAL "${parent}/execution-packages" OR
   root STREQUAL EXECUTION_SOURCE OR root STREQUAL TOOLKIT_SOURCE OR
   NOT EXISTS "${EXECUTION_SOURCE}/CMakePresets.json" OR
   NOT EXISTS "${TOOLKIT_SOURCE}/cpp-library.cmake")
  message(FATAL_ERROR "Refusing unscoped verification root: ${root}")
endif()
foreach(source EXECUTION_SOURCE TOOLKIT_SOURCE)
  cmake_path(IS_PREFIX root "${${source}}" NORMALIZE contains_source)
  if(contains_source)
    message(FATAL_ERROR "Verification root contains a source tree: ${root}")
  endif()
endforeach()
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}")
find_program(ctest NAMES ctest REQUIRED)

function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(APPEND "${root}/commands.log" "Command: ${ARGV}\nExit: ${result}\n${output}\n${error}\n")
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Command (${result}): ${ARGV}\n${output}\n${error}")
  endif()
  if(NOT error STREQUAL "")
    message("${error}")
  endif()
endfunction()

set(settings "-DCPM_cpp-library_SOURCE:PATH=${TOOLKIT_SOURCE}" -DBUILD_TESTING=OFF
  -DSTLAB_EXECUTION_INSTALL=ON -DCPP_LIBRARY_VERSION=1.0.0)
foreach(setting STLAB_EXECUTION_SHARED STLAB_TASK_SYSTEM)
  if(DEFINED ${setting} AND NOT "${${setting}}" STREQUAL "")
    list(APPEND settings "-D${setting}=${${setting}}")
  endif()
endforeach()
if(DEFINED TEST_MAKE_PROGRAM AND NOT TEST_MAKE_PROGRAM STREQUAL "")
  list(APPEND settings "-DCMAKE_MAKE_PROGRAM:FILEPATH=${TEST_MAKE_PROGRAM}")
endif()
if(DEFINED TEST_COMPILER AND NOT TEST_COMPILER STREQUAL "")
  list(APPEND settings "-DCMAKE_CXX_COMPILER:FILEPATH=${TEST_COMPILER}")
endif()
set(prefix "${root}/prefix")
run("${CMAKE_COMMAND}" --preset=install -S "${EXECUTION_SOURCE}" -B "${root}/library" ${settings})
run("${CMAKE_COMMAND}" --build "${root}/library" --parallel 8)
run("${CMAKE_COMMAND}" --install "${root}/library" --prefix "${prefix}")
file(GLOB_RECURSE configs "${prefix}/*Config.cmake")
foreach(config IN LISTS configs)
  file(READ "${config}" content)
  if(content MATCHES "find_dependency\\(stlab[ )]" OR config MATCHES "/stlabConfig.cmake$")
    message(FATAL_ERROR "Execution installation must not depend on STLab: ${config}")
  endif()
endforeach()
file(GLOB_RECURSE versions "${prefix}/*stlab-executionConfigVersion.cmake")
list(LENGTH versions count)
if(NOT count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one independent execution version config.")
endif()
file(READ "${versions}" version)
if(NOT version MATCHES "set\\(PACKAGE_VERSION \"1.0.0\"\\)")
  message(FATAL_ERROR "Wrong independently configured execution version: ${version}")
endif()
if(EXISTS "${prefix}/include/stlab/config.hpp" OR EXISTS "${prefix}/include/stlab/concurrency/future.hpp")
  message(FATAL_ERROR "Execution installed STLab-owned headers.")
endif()
foreach(standard 17 20)
  run("${CMAKE_COMMAND}" -S "${EXECUTION_SOURCE}/test/package" -B "${root}/consumer-${standard}"
    -G Ninja "-DCMAKE_PREFIX_PATH:PATH=${prefix}" "-DCMAKE_CXX_STANDARD=${standard}"
    "-DEXECUTION_PREFIX:PATH=${prefix}" -DCMAKE_BUILD_TYPE=Release)
  run("${CMAKE_COMMAND}" --build "${root}/consumer-${standard}" --parallel 8)
  run("${ctest}" --test-dir "${root}/consumer-${standard}" --output-on-failure)
endforeach()
message(STATUS "PASS standalone execution package: ${prefix}")
