# Distributed under the Boost Software License, Version 1.0.
# Platform discovery retained from STLab's StlabUtil.cmake.

include(CheckCXXSymbolExists)

# Returns the target's threading system in result_var.
function(execution_detect_thread_system result_var)
  find_package(Threads QUIET)
  if(CMAKE_SYSTEM_NAME STREQUAL "Emscripten" AND NOT STLAB_EMSCRIPTEN_PTHREADS)
    set(result "none")
  elseif(CMAKE_USE_WIN32_THREADS_INIT)
    set(result "win32")
  elseif(CMAKE_USE_PTHREADS_INIT)
    if(CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
      set(result "pthread-emscripten")
    elseif(APPLE)
      set(result "pthread-apple")
    else()
      set(result "pthread")
    endif()
  else()
    set(result "none")
  endif()
  set(${result_var} ${result} PARENT_SCOPE)
endfunction()

# Returns the target's default task system in result_var.
function(execution_detect_task_system result_var)
  find_package(Threads QUIET)
  if(APPLE)
    set(result "libdispatch")
  elseif(WIN32)
    set(result "windows")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
    if(STLAB_EMSCRIPTEN_PTHREADS)
      set(result "portable")
    else()
      set(result "emscripten")
    endif()
  else()
    # [DEPENDENCY] https://github.com/swiftlang/swift-corelibs-libdispatch
    find_package(libdispatch)
    if(libdispatch_FOUND)
      set(result "libdispatch")
    else()
      set(result "portable")
    endif()
  endif()
  set(${result_var} ${result} PARENT_SCOPE)
endfunction()

# Returns the target's default main executor in result_var.
function(execution_detect_main_executor result_var)
  execution_detect_task_system(task_system)
  if(task_system STREQUAL "libdispatch")
    set(result "libdispatch")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
    set(result "emscripten")
  elseif(Qt6Core_FOUND)
    set(result "qt6")
  elseif(Qt5Core_FOUND)
    set(result "qt5")
  else()
    set(result "none")
  endif()
  set(${result_var} ${result} PARENT_SCOPE)
endfunction()
