name: Windows shared execution

on: [push, pull_request]

jobs:
  shared:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [test-shared, test-portable-shared]
    steps:
      - uses: actions/checkout@v7
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
      - run: cmake --preset=${{ matrix.preset }}
      - run: cmake --build --preset=${{ matrix.preset }}
      - run: ctest --preset=${{ matrix.preset }}
